name: trusted_time
description: Tamper-proof, offline-safe, multi-source trusted time for Flutter. Provides reliable timestamps immune to system clock manipulation.
version: 1.0.0
homepage: https://github.com/Sahad2701/trusted_time
repository: https://github.com/Sahad2701/trusted_time
issue_tracker: https://github.com/Sahad2701/trusted_time/issues
documentation: https://pub.dev/documentation/trusted_time/latest/

environment:
  sdk: ^3.9.2
  flutter: '>=3.35.4'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  flutter_secure_storage: ^10.0.0
  plugin_platform_interface: ^2.1.8
  intl: ^0.20.2
  ntp: ^2.0.0
  web: ^0.5.1
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.trusted_time
        pluginClass: TrustedTimePlugin
      ios:
        pluginClass: TrustedTimePlugin
      macos:
        pluginClass: TrustedTimePlugin
      windows:
        pluginClass: TrustedTimePlugin
      linux:
        pluginClass: TrustedTimePlugin
      web:
        pluginClass: TrustedTimeWeb
        fileName: src/platform/trusted_time_web.dart

topics:
  - time
  - ntp
  - security
  - tamper-proof
  - anti-fraud
